from automated_builds_pipeline.pr_comment import render_pr_comment
from automated_builds_pipeline.stats import HeroStats, ItemWindowEvidence, WindowObservation, append_window


OBSERVED_AT = "2026-05-05T12:00:00Z"


def make_diff() -> dict:
    return {
        "hero": "Karnok",
        "window_id": "May 06",
        "proposed_changes": {
            "archetype_updates": [
                {
                    "archetype": "Axe",
                    "missing_items": [{"item": "Hunting Knife"}],
                }
            ],
            "archetype_additions": [],
            "item_removal_candidates": [],
            "archetype_removal_candidates": [],
        },
    }


def add_row(
    stats: HeroStats,
    source: str,
    window: str,
    item: str = "Hunting Knife",
    *,
    present: bool = True,
    frequency: float | None = None,
    sample_count: int | None = None,
    archetypes_seen: list[str] | None = None,
) -> None:
    append_window(
        stats,
        source,
        WindowObservation(
            window_id=f"{source}:{window}",
            observed_at=OBSERVED_AT,
            items=[
                ItemWindowEvidence(
                    item,
                    present=present,
                    frequency=frequency,
                    sample_count=sample_count,
                    archetypes_seen=archetypes_seen or [],
                )
            ],
        ),
    )


def test_trajectory_table_populates_per_source_oldest_to_newest_and_skips_empty_sources():
    stats = HeroStats(hero="Karnok")
    add_row(stats, "bazaardb", "Apr 29", frequency=0.42, sample_count=510)
    add_row(stats, "bazaardb", "May 06", frequency=0.38, sample_count=487)
    add_row(stats, "mobalytics_meta_builds", "v537", present=False)

    rendered = render_pr_comment(make_diff(), stats)

    assert "| bazaardb | bazaardb:Apr 29 | yes | 0.42 | 510 |" in rendered
    assert "| bazaardb | bazaardb:May 06 | yes | 0.38 | 487 |" in rendered
    assert "| mobalytics_meta_builds | mobalytics_meta_builds:v537 | no | - | - |" in rendered
    assert "bazaar_builds_net" not in rendered
    assert rendered.index("bazaardb:Apr 29") < rendered.index("bazaardb:May 06")


def test_cross_archetype_section_appears_only_with_multiple_archetypes_seen():
    stats = HeroStats(hero="Karnok")
    add_row(stats, "bazaardb", "Apr 29", archetypes_seen=["Axe"])

    single = render_pr_comment(make_diff(), stats)

    assert "**Cross-archetype usage**" not in single

    add_row(stats, "bazaar_builds_net", "2026-W18", archetypes_seen=["Wide Weapons"])
    multiple = render_pr_comment(make_diff(), stats)

    assert "**Cross-archetype usage**" in multiple
    assert '- "Axe": 1 windows' in multiple
    assert '- "Wide Weapons": 1 windows' in multiple


def test_empty_proposed_changes_returns_no_proposals_fallback_line():
    stats = HeroStats(hero="Karnok")
    rendered = render_pr_comment(
        {
            "window_id": "May 06",
            "proposed_changes": {
                "archetype_updates": [],
                "archetype_additions": [],
                "item_removal_candidates": [],
                "archetype_removal_candidates": [],
            },
        },
        stats,
    )

    assert rendered == "No supporting evidence sections; this run produced no proposals."


def test_history_windows_limits_rows_per_source():
    stats = HeroStats(hero="Karnok")
    add_row(stats, "bazaardb", "Apr 15")
    add_row(stats, "bazaardb", "Apr 29")
    add_row(stats, "bazaardb", "May 06")

    rendered = render_pr_comment(make_diff(), stats, history_windows=2)

    assert "bazaardb:Apr 15" not in rendered
    assert "bazaardb:Apr 29" in rendered
    assert "bazaardb:May 06" in rendered


def test_footer_includes_diff_window_id():
    stats = HeroStats(hero="Karnok")
    add_row(stats, "bazaardb", "May 06")

    rendered = render_pr_comment(make_diff(), stats)

    assert "Generated by automated-builds-bot from karnok_stats.json window May 06." in rendered


def test_retirement_review_candidates_include_affected_item_history():
    stats = HeroStats(hero="Karnok")
    add_row(stats, "bazaardb", "Apr 29", item="Battle Axe", present=False)
    diff = {
        "hero": "Karnok",
        "window_id": "May 06",
        "proposed_changes": {
            "archetype_updates": [],
            "archetype_additions": [],
            "item_removal_candidates": [],
            "archetype_removal_candidates": [
                {
                    "archetype": "Axe",
                    "item": "Battle Axe",
                    "affected_items": ["Battle Axe"],
                    "retirement_type": "whole_build_review",
                }
            ],
        },
    }

    rendered = render_pr_comment(diff, stats)

    assert "### Axe / Battle Axe" in rendered
    assert "| bazaardb | bazaardb:Apr 29 | no | - | - |" in rendered


def test_supporting_comment_includes_game_change_signal_metadata():
    stats = HeroStats(hero="Karnok")
    add_row(stats, "bazaardb", "Apr 29", item="Old Support", present=False)
    diff = {
        "hero": "Karnok",
        "window_id": "May 06",
        "proposed_changes": {
            "archetype_updates": [],
            "archetype_additions": [],
            "item_removal_candidates": [
                {
                    "archetype": "Axe",
                    "item": "Old Support",
                    "signal_evidence": [
                        {
                            "id": "rename-old-support",
                            "type": "renamed_card",
                            "effective_date": "2026-05-01",
                            "replacement_item": "New Support",
                            "source_url": "https://example.test/signal",
                        }
                    ],
                }
            ],
            "archetype_removal_candidates": [],
        },
    }

    rendered = render_pr_comment(diff, stats)

    assert "**Game-change signals**" in rendered
    assert "- rename-old-support; renamed_card; 2026-05-01; replacement: New Support; https://example.test/signal" in rendered
