"""Render supporting-evidence PR comments from sidecar history."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any, Optional

from automated_builds_pipeline.stats import HeroStats, SUPPORTED_SOURCES, WindowItemStats


@dataclass(frozen=True)
class EvidenceTarget:
    archetype: Optional[str]
    item: Optional[str] = None


def render_pr_comment(diff: dict, stats: HeroStats, *, history_windows: int = 6) -> str:
    targets = _evidence_targets(diff)
    if not targets:
        return "No supporting evidence sections; this run produced no proposals."

    lines = [
        "## Supporting Evidence",
        "",
        "This comment surfaces per-window history from the stats sidecar. The PR body is the canonical proposal.",
    ]
    for target in targets:
        lines.extend(["", f"### {_heading(target)}", "", "**Trajectory** (last K windows per source, K = history_windows parameter):", ""])
        lines.extend(_trajectory_table(target, stats, history_windows))
        if target.item is not None:
            cross_archetypes = _cross_archetype_usage(target.item, stats, history_windows)
            if len(cross_archetypes) >= 2:
                lines.extend(["", "**Cross-archetype usage** (items only, skip archetype-only rows):", ""])
                for archetype, count in sorted(cross_archetypes.items()):
                    lines.append(f'- "{archetype}": {count} windows')

    lines.extend(["", f"Generated by automated-builds-bot from {_stats_filename(stats.hero)} window {_window_id(diff)}."])
    return "\n".join(lines) + "\n"


def _evidence_targets(diff: dict) -> list[EvidenceTarget]:
    proposed = diff.get("proposed_changes", {})
    if not isinstance(proposed, dict):
        return []

    targets: list[EvidenceTarget] = []
    for update in _dict_rows(proposed.get("archetype_updates")):
        for item in _dict_rows(update.get("missing_items")):
            targets.append(EvidenceTarget(archetype=_str_or_none(update.get("archetype")), item=_str_or_none(item.get("item"))))

    for addition in _dict_rows(proposed.get("archetype_additions")):
        archetype = _str_or_none(addition.get("tag") or addition.get("archetype"))
        for item in [*_dict_rows(addition.get("candidate_core")), *_dict_rows(addition.get("candidate_support"))]:
            targets.append(EvidenceTarget(archetype=archetype, item=_str_or_none(item.get("item"))))

    for removal in _dict_rows(proposed.get("item_removal_candidates")):
        targets.append(EvidenceTarget(archetype=_str_or_none(removal.get("archetype")), item=_str_or_none(removal.get("item"))))

    for removal in _dict_rows(proposed.get("archetype_removal_candidates")):
        archetype = _str_or_none(removal.get("archetype"))
        affected_items = [
            _str_or_none(item)
            for item in removal.get("affected_items", [])
            if _str_or_none(item) is not None
        ] if isinstance(removal.get("affected_items"), list) else []
        item = _str_or_none(removal.get("item"))
        for affected in affected_items or ([item] if item else []):
            targets.append(EvidenceTarget(archetype=archetype, item=affected))
        if not affected_items and item is None:
            targets.append(EvidenceTarget(archetype=archetype))

    return [target for target in targets if target.archetype or target.item]


def _trajectory_table(target: EvidenceTarget, stats: HeroStats, history_windows: int) -> list[str]:
    lines = [
        "| Source | Window | Present | Freq | Sample |",
        "|---|---|---|---|---|",
    ]
    if target.item is None:
        return lines
    for source in sorted(SUPPORTED_SOURCES):
        rows = _item_history(stats, target.item, source, history_windows)
        for row in rows:
            lines.append(
                f"| {source} | {row.window_id} | {_present(row)} | {_frequency(row)} | {_sample(row)} |"
            )
    return lines


def _cross_archetype_usage(item: str, stats: HeroStats, history_windows: int) -> Counter[str]:
    usage: Counter[str] = Counter()
    for source in sorted(SUPPORTED_SOURCES):
        for row in _item_history(stats, item, source, history_windows):
            for archetype in set(row.archetypes_seen):
                usage[archetype] += 1
    return usage


def _item_history(stats: HeroStats, item: str, source: str, history_windows: int) -> list[WindowItemStats]:
    if history_windows <= 0:
        return []
    return stats.item_history(item, source, limit=history_windows)


def _dict_rows(value: Any) -> list[dict[str, Any]]:
    return [row for row in value if isinstance(row, dict)] if isinstance(value, list) else []


def _heading(target: EvidenceTarget) -> str:
    if target.item is None:
        return target.archetype or "unknown"
    return f"{target.archetype or 'unknown'} / {target.item}"


def _present(row: WindowItemStats) -> str:
    return "yes" if row.present else "no"


def _frequency(row: WindowItemStats) -> str:
    if row.frequency is None:
        return "-"
    return f"{row.frequency:.2f}"


def _sample(row: WindowItemStats) -> str:
    return "-" if row.sample_count is None else str(row.sample_count)


def _str_or_none(value: Any) -> Optional[str]:
    return str(value) if value is not None else None


def _window_id(diff: dict) -> str:
    return str(diff.get("window_id") or "unknown")


def _stats_filename(hero: str) -> str:
    slug = "_".join("".join(char.casefold() if char.isalnum() else " " for char in hero).split())
    return f"{slug or 'unknown'}_stats.json"
